### ISSUE TITLE
似乎无法点击执行客户端命令

### ISSUE THREAD

**Issue by alex3236** [Fallen-Breath/LetMeClickAndSend#1]
## Description

如题

## To Reproduce

```
/tellraw @a {"text":"[+V]","clickEvent":{"action":"run_command","value":"/highlightWaypoint -296 69 -509"}}
```

其中 `/highlightWaypoint -296 69 -509` 是一个客户端命令。

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.19.2'
- Mod version: '1.0.0'

**Comment by Fallen-Breath** [comment]
请给出正确的复现环境，原版情况下并不存在 `/highlightWaypoint` 这一客户端命令

**Comment by alex3236** [comment]
> 请给出正确的复现环境，原版情况下并不存在 `/highlightWaypoint` 这一客户端命令

原版似乎根本没有纯客户端命令吧（
纯客户端命令例如 VoxelMap 或 xaero-map-addition 高亮坐标的 `/highlightWaypoint`
[clientcommands](https://github.com/Earthcomputer/clientcommands) 的任意命令

[打包的 Mod](https://github.com/Fallen-Breath/LetMeClickAndSend/files/9895007/mods.zip)

**Comment by Fallen-Breath** [comment]
请给出完整的正确的复现环境，而非若个依赖都不完善的 mod，我不是来配置模组依赖的

请确定并明确与该 issue 相关的 mod 是哪些，不要一股脑把所有可能相关的 mod 都放出来，除非你确定该 mod 存在与此 issue 相关的问题

除此之外，请给出你期望得到的现象，以及如何复现你期望得到的现象

**Comment by alex3236** [comment]
试试 https://modrinth.com/mod/journeymap 不需要额外依赖。
这些 Mod 都注册了纯客户端命令啊... 实现方式应该没多大区别

例如 `/highlightWaypoint` 是 VoxelMap JourneyMap XaeroMapAddition 都有并且格式一致的命令
点击 tellraw 的 run_command action，例如点击 [`TISUnion/Here`](https://github.com/TISUnion/Here) 的 `[+V]` 本应执行纯客户端命令 `/highlightWaypoint x y z`，在小地图上高亮坐标点。
1.19.2 中显示未知命令，但手动执行正常。

**Comment by Fallen-Breath** [comment]
**请给出正确的复现环境**，第三遍了

在以下环境下：
- Minecraft 1.19.2
- Fabric API 0.43.0+1.19.2
- Journeymap 5.9.0beta2

无论是否安装此 Mod，使用 To Reproduce 中的指令并点击，以及直接输入 `/highlightWaypoint -296 69 -509`，均显示未知命令

**Comment by alex3236** [comment]
排查了一下 VoxelMap 可以通过 `[x, y, z]` 识别坐标点，但 tellraw 出来的依然未知命令
xaero-map-addition 的命令是 [OMMC](https://github.com/plusls/oh-my-minecraft-client) 实现的 情况也一样

**Comment by Fallen-Breath** [comment]
**请给出正确的复现环境**，第四遍

> 排查了一下 VoxelMap 可以通过 `[x, y, z]` 识别坐标点

在以下环境下，在聊天栏输入 `[1, 2, 3]`，无任何可点击文本出现，无法复现：

- Minecraft 1.19.2
- Fabric API 0.43.0+1.19.2
- VoxelMap 1.11.10

**Comment by Fallen-Breath** [comment]
请给出完善的 issue 描述，包括：

- 不包含本 mod 时的现象是什么
- 包含本 mod 时现象是什么
- 你期望有什么表现

且提供了正确的复现环境，包括：

- 完整准确的 mod 列表
- 如何复现所述 issue

再考虑重新 open 此 issue
