### ISSUE TITLE
添加1.20.2支持

### ISSUE THREAD

**Issue by Adogs1** [Fallen-Breath/LetMeClickAndSend#2]
### Motivation

在最新版本中能够使用

### Description

添加对1.20.2的支持

**Comment by wucy777** [comment]
> ### 赋予动机
> 在最新版本中能够使用
> 
> ### 描述
> 添加对1.20.2的支持
> 
> ### 其他资讯
> _没有回应_

在https://modrinth.com/mod/letmeclickandsend寻找到1.20.2支持
